CREATE TABLE Contractor
(
  salary NUMERIC(30) NOT NULL,
  Gender VARCHAR(100) NOT NULL,
  CID NUMERIC(30) NOT NULL,
  contractorName VARCHAR(100) NOT NULL,
  PRIMARY KEY (CID)
);

CREATE TABLE ConstructionProject
(
  projectName VARCHAR(100) NOT NULL,
  PiD NUMERIC(30) NOT NULL,
  startDate DATE NOT NULL,
  CID NUMERIC(30) NOT NULL,
  PRIMARY KEY (PiD),
  FOREIGN KEY (CID) REFERENCES Contractor(CID)
);

CREATE TABLE Area
(
  AreaName VARCHAR(100) NOT NULL,
  AreaId NUMERIC(30) NOT NULL,
  PRIMARY KEY (AreaId)
);

CREATE TABLE projectIn
(
  PiD NUMERIC(30) NOT NULL,
  AreaId NUMERIC(30) NOT NULL,
  PRIMARY KEY (PiD, AreaId),
  FOREIGN KEY (PiD) REFERENCES ConstructionProject(PiD),
  FOREIGN KEY (AreaId) REFERENCES Area(AreaId)
);

CREATE TABLE Worker
(
  workerName VARCHAR(100) NOT NULL,
  WID NUMERIC(30) NOT NULL,
  Gender VARCHAR(100) NOT NULL,
  YearsOfWork VARCHAR(100) NOT NULL,
  CID NUMERIC(30) NOT NULL,
  PRIMARY KEY (WID),
  FOREIGN KEY (CID) REFERENCES Contractor(CID)
);